import car2 from "../../assets/car2.jpg";
import hire from "../../assets/hireDriver.jpg";
import car1 from "../../assets/car1.jpg";

const posts = [
    {
        id: 1,
        image: car1,
        title: 'Dashain Travels Made Easy with Spark Car Rental: Pre-Booking Now Open!',
        description: 'This year, Spark Car Rental is here to make your Dashain travels easier than ever...',
        descriptionImage:car2,
        conclusion: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        day: '16',
        month: 'Sep',
        date: '2024-09-16', // Using ISO date format for better comparison
      },
      {
        id: 2,
        image: hire,
        title: 'How to Choose the Best Car Rental in Kathmandu: Tips and Factors to Consider',
        description: "For tourists, the critical thing is making their decision on where to choose their best car rental in Kathmandu. ",
        descriptionImage:car1,
        conclusion: 'Reputation, terms, pricing, customer service, and vehicle options all play major roles in choosing the best car rental company in Kathmandu. Spark Car earns our highest rating thanks to its stellar reputation and extensive facilities.  Spark Car guarantees a memorable rental experience in Kathmandu, Nepal, by providing quality in every way. We stand out due to our dedication to client satisfaction, affordable prices, and varied fleet of automobiles. Choose Spark Car for unparalleled service, convenience, and a memorable journey in Kathmandu.',
        day: '25',
        month: 'Aug',
        date: '2024-08-25',
      },
      {
        id: 3,
        image: car2,
        title: 'Why Customers Love Renting from Spark Car',
        description: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        descriptionImage:car1,
        conclusion: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        day: '09',
        month: 'sep',
        date: '2024-08-12',
      },
      {
        id: 4,
        image: car2,
        title: 'How Good and Bad Driving Affects Road Traffic?',
        description: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        descriptionImage:hire,
        conclusion: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        day: '07',
        month: 'jun',
        date: '2024-08-05',
      },
      {
        id: 5,
        image: hire,
        title: 'Safe Driving Practices You Should Follow',
        description: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        descriptionImage:hire,
        conclusion: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        day: '15',
        month: 'Jul',
        date: '2024-07-15',
      },
      {
        id: 6,
        image: car1,
        title: 'Car Maintenance Tips for Long Road Trips',
        description: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        descriptionImage:hire,
        conclusion: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        day: '02',
        month: 'Aug',
        date: '2024-08-02',
      },
      {
        id: 7,
        image: car2,
        title: 'Best Routes to Travel Around Nepal by Car',
        description: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        descriptionImage:hire,
        conclusion: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        day: '22',
        month: 'Sep',
        date: '2024-09-22',
      },
      {
        id: 8,
        image: hire,
        title: 'Why Electric Vehicles are the Future',
        description: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        descriptionImage:hire,
        conclusion: 'Hiace van rental in Kathmandu is best when traveling in a group, renting a Hiace...',
        day: '30',
        month: 'Oct',
        date: '2024-10-30',
      },
];

export default posts; 
